webmonitor/config/routes.rb
Webmonitor::Application.routes.draw do

  devise_for :users
  resources :temperatures
  resources :profiles

  match "dashboard" => "dashboard#index", :as => :dashboard
  match "get_temperature" => "dashboard#get_temperature", :as => :get_temperature
  match "current_temperature" => "dashboard#current_temperature", :as => :current_temperature
  
  match "sensors/info" => "sensors#info", :as => :info_sensor

  resource :system_configurations
  resource :charts
  resource :reports do
    get :export
  end
  resources :notifications
  resources :sensors
  resources :roles

  root :to => 'dashboard#index'

end

webmonitor/app/views/shared/_menu.html.erb
<div id="nav-menu">
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to('Dashboard', dashboard_path) %></li>
      <li><%= link_to('Users', profiles_path) %></li>
      <li><%= link_to('Temperatures', temperatures_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% end %>
  </ul>
</div>

webmonitor/app/views/shared/_topbar.html.erb
<div class="topbar">
  <div class="fill">
    <div class="container">
      <% if user_signed_in? %>
      <%= link_to "Servidor de Dados e Monitoramento", dashboard_path, :class => "brand" %>
      <ul class="nav">
        <li class="<%= current_css(:dashboard) %>"><%= link_to "Home", dashboard_path %></li>
        <li class="<%= current_css(:reports) %>"><%= link_to "Relatórios", reports_path %></li>
        <li class="<%= current_css(:charts) %>"><%= link_to "Gráficos", charts_path %></li>
        <li class="<%= current_css(:sensors) %>"><%= link_to "Dispositivos", sensors_path %></li>
        <li class="dropdown">
        <a class="dropdown-toggle" href="#contact">Configura&ccedil;&otilde;es</a>
        <ul class="dropdown-menu">
          <li class="<%= current_css(:system_configurations) %>"><%= link_to "Geral", edit_system_configurations_path %></li>
          <li class="<%= current_css(:notifications) %>"><%= link_to "Notificações", notifications_path %></li>
          <li class="<%= current_css(:roles) %>"><%= link_to "Usuários", roles_path %></li>
        </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</div>