webmonitor/config/routes.rb
Webmonitor::Application.routes.draw do

  devise_for :users
  resources :temperatures
  resources :profiles

  match "dashboard" => "dashboard#index", :as => :dashboard
  match "get_temperature" => "dashboard#get_temperature", :as => :get_temperature
  match "current_temperature" => "dashboard#current_temperature", :as => :current_temperature
  
  match "sensors/info" => "sensors#info", :as => :info_sensor

  resource :system_configurations
  resource :charts
  resource :reports do
    get :export
  end
  resources :notifications
  resources :sensors
  resources :roles

  root :to => 'dashboard#index'

end

webmonitor/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
end

webmonitor/app/views/roles/_description.html.erb
<div class="span4">
  <h2>Descri&ccedil;&atilde;o</h2>
  <dl>

    <dt>Descri&ccedil;&atildeo</dt>
    <dd>Nome ou descri&ccedil;&atilde;o do sensor/dispositivo utilizado para descrev&ecirc;-lo</dd>

    <dt>Endere&ccedil;o IP</dt>
    <dd>Endere&ccedil;o IP do dispositivo.</dd>

  </dl>
</div>

webmonitor/app/views/roles/_form.html.erb
<%= form_for @user, :url => roles_path do |f| %>
  <fieldset>
    <legend>Usu&aacute;rio</legend>

    <div class="clearfix">
      <%= f.label :email, nil, :class => "obligatory" %>
      <div class="input">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :password, nil, :class => "obligatory" %>
      <div class="input">
        <%= f.password_field :email %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :password_confirmation, nil, :class => "obligatory" %>
      <div class="input">
        <%= f.password_field :password_confirmation %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Salvar", :class => "btn primary" %>
      <%= button_tag "Cancelar", :type => :reset, :class => "btn" %>
    </div>

  </fieldset>
<% end %>

webmonitor/app/views/roles/edit.html.erb
<div class="page-header">
  <h1>Editar Usu&aacute;rio</h1>
</div>

<div class="row">
  <div class="span10">

    <%= render "form" %>

  </div>

</div>

webmonitor/app/views/roles/index.html.erb
<div class="page-header">
  <h1>Usu&aacute;rios</h1>
</div>

<div class="row">

  <div class="span14">
    <table class="zebra-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>E-mail</th>
          <th>A&ccedil;&otilde;es</th>
        </tr>
      </thead>
      <% @users.each do |u| %>
        <tr>
        <td><%= u.id %></td>
        <td><%= u.email %></td>
        <td>
          <%= link_to "R", roles_path(u), :method => :delete, :confirm => "Está certo disto?", :class => "btn danger" %>
          <%= link_to "E", edit_role_path(u), :class => "btn success" %>
        </td>
      </tr>
    <% end %>
    </table>

    <div class="actions">
      <%= link_to "Novo Usuário", new_role_path, :class => "btn primary" %>
    </div>

  </div>

</div>

webmonitor/app/views/roles/new.html.erb
<div class="page-header">
  <h1>Novo Usu&aacute;rio</h1>
</div>

<div class="row">
  <div class="span10">

    <%= render "form" %>

  </div>

</div>