webmonitor/config/routes.rb
Webmonitor::Application.routes.draw do

  devise_for :users
  resources :temperatures
  resources :profiles

  match "dashboard" => "dashboard#index", :as => :dashboard
  match "get_temperature" => "dashboard#get_temperature", :as => :get_temperature
  match "current_temperature" => "dashboard#current_temperature", :as => :current_temperature
  
  match "sensors/info" => "sensors#info", :as => :info_sensor

  resource :system_configurations
  resource :charts
  resource :reports do
    get :export
  end
  resources :notifications
  resources :sensors
  resources :roles

  root :to => 'dashboard#index'

end

webmonitor/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to profiles_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to profiles_path, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :ok }
    end
  end
end

webmonitor/app/views/profiles/_form.html.erb
<%= form_for(@user, :url => profile_path(@user)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webmonitor/app/views/profiles/edit.html.erb
<h1>Editing temperature</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperature %> |
<%= link_to 'Back', temperatures_path %>

webmonitor/app/views/profiles/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>E-mail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', profile_path(user) %></td>
    <td><%= link_to 'Edit', edit_profile_path(user) %></td>
    <td><%= link_to 'Destroy', profiles_path(user), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

webmonitor/app/views/profiles/new.html.erb
<h1>New user </h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

webmonitor/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>E-mail:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_profile_path(@user) %> |
<%= link_to 'Back', profiles_path %>