webmonitor/config/routes.rb
Webmonitor::Application.routes.draw do

  devise_for :users
  resources :temperatures
  resources :profiles

  match "dashboard" => "dashboard#index", :as => :dashboard
  match "get_temperature" => "dashboard#get_temperature", :as => :get_temperature
  match "current_temperature" => "dashboard#current_temperature", :as => :current_temperature
  
  match "sensors/info" => "sensors#info", :as => :info_sensor

  resource :system_configurations
  resource :charts
  resource :reports do
    get :export
  end
  resources :notifications
  resources :sensors
  resources :roles

  root :to => 'dashboard#index'

end

webmonitor/app/models/sensor.rb
#coding: utf-8
class Sensor < ActiveRecord::Base
    validates_presence_of :description
    has_many :temperatures

    def alert
      read_attribute(:alert) ? "Sim" : "Não"
    end

    def temperature
       Watcher.get_temperature( ip_address, token )
    end

    def is_alert?(temperature)
      temperature.to_f > max_temperature or temperature.to_f < min_temperature
    end

    def is_critical?(temperature)
      ss = SystemConfiguration.first
      if ss
        critical_level = ss.critical_level
      end
      not is_alert?(temperature.to_f) and ( temperature.to_f > ( max_temperature - critical_level.to_f ) or temperature.to_f < ( min_temperature - critical_level ) )
    end

    def is_normal?(temperature)
      not is_critical?(temperature) and not is_alert?(temperature)
    end
end

webmonitor/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

  def index
    @sensors = Sensor.all
    respond_to do |format|
      format.html
    end
  end

  def new
    @sensor = Sensor.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @sensor = Sensor.new( params[:sensor] )
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to sensors_path, :notice => "Sensor cadastrado com sucesso" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @sensor = Sensor.find(params[:id])
    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to sensors_path, :notice => "Sensor atualizado com sucesso" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @sensor = Sensor.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def destroy
    @sensor = Sensor.find( params[:id] )
    @sensor.destroy
    flash[:notice] = "Sensor removido com sucesso!"
    respond_to do |format|
      format.html { redirect_to sensors_path }
    end
  end

  def info
    respond_to do |format|
      format.json { render :json => Watcher.get_info( params[:ip], params[:token] ) }
    end
  end

end

webmonitor/app/helpers/sensors_helper.rb
module SensorsHelper
  def image_tag_sensor(sensor, temperature)
    if sensor.is_normal?(temperature)
      image_tag "arduino_green.jpg", :class => "thumbnail"
    else
      if sensor.is_critical?(temperature)
        image_tag "arduino_yellow.jpg", :class => "thumbnail"
      else
        image_tag "arduino_red.jpg", :class => "thumbnail"
      end
    end
  end
end

webmonitor/app/views/sensors/_description.html.erb
<div class="span4">
  <h2>Descri&ccedil;&atilde;o</h2>
  <dl>

    <dt>Descri&ccedil;&atildeo</dt>
    <dd>Nome ou descri&ccedil;&atilde;o do sensor/dispositivo utilizado para descrev&ecirc;-lo</dd>

    <dt>Endere&ccedil;o IP</dt>
    <dd>Endere&ccedil;o IP do dispositivo.</dd>

    <dt>Chave secreta</dt>
    <dd>Chave secreta utilizada para a comunica&ccedil;&atilde;o segura entre o sistema supervisor e os dispositivos (sensores).</dd>

  </dl>
</div>

webmonitor/app/views/sensors/_form.html.erb
<% content_for :javascript do %>
  <script type="text/javascript" language="javascript" charset="utf-8">
  //<![CDATA[
    $('.info').click(function(){
        $.get("<%= info_sensor_path %>", { ip: $('#sensor_ip_address').val(), token: $('#sensor_token').val() }, function(data){
          $('#sensor_max_temperature').val(data.max_temperature);
          $('#sensor_min_temperature').val(data.min_temperature);
        });
    });
  //]]>
  </script>
<% end %>
<%= form_for @sensor do |f| %>
  <fieldset>
  <legend>Dispositivo</legend>

  <div class="clearfix">
    <%= f.label :description, nil, :class => "obligatory" %>
    <div class="input">
      <%= f.text_field :description %>
      <span class="help-block"><strong>Nota:</strong> Nome ou local</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :ip_address, nil, :class => "obligatory" %>
    <div class="input">
      <%= f.text_field :ip_address %>
      <span class="help-block"><strong>Nota:</strong> Endere&ccedil;o IP do dispositivo</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :token, nil, :class => "obligatory" %>
    <div class="input">
      <%= f.text_field :token, :class => "xlarge" %>
      <span class="help-block"><strong>Nota:</strong> n&atilde;o utilize espa&ccedil;os em branco</span>
    </div>
  </div>

  <%= f.hidden_field :max_temperature %>
  <%= f.hidden_field :min_temperature %>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn primary" %>
    <%= button_tag "Cancelar", :type => :reset, :class => "btn" %>
    <%= button_tag "Carregar Informações", :type => :button, :class => "btn info" %>
  </div>

</fieldset>
<% end %>

webmonitor/app/views/sensors/edit.html.erb
<div class="page-header">
  <h1>Editar Dispositivo</h1>
</div>

<div class="row">
  <div class="span10">

    <%= render "form" %>

  </div>

  <%= render "description" %>

</div>

webmonitor/app/views/sensors/index.html.erb
<div class="page-header">
  <h1>Dispositivo</h1>
</div>

<div class="row">

  <div class="span14">
    <table class="zebra-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Descri&ccedil;&atilde;o</th>
          <th>Alerta</th>
          <th>A&ccedil;&otilde;es</th>
        </tr>
      </thead>
      <% @sensors.each do |s| %>
        <tr>
        <td><%= s.id %></td>
        <td><%= s.description %></td>
        <td><%= s.alert %></td>
        <td>
          <%= link_to "R", sensor_path(s), :method => :delete, :confirm => "Está certo disto?", :class => "btn danger" %>
          <%= link_to "E", edit_sensor_path(s), :class => "btn success" %>
        </td>
      </tr>
    <% end %>
    </table>

    <div class="actions">
      <%= link_to "Novo Dispositivo", new_sensor_path, :class => "btn primary" %>
    </div>

  </div>

</div>

webmonitor/app/views/sensors/new.html.erb
<div class="page-header">
  <h1>Novo Dispositivo</h1>
</div>

<div class="row">
  <div class="span10">

    <%= render "form" %>

  </div>

  <%= render "description" %>

</div>